services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: "" # see https://github.com/docker-library/docker/pull/166

stages:
  - build

build:
  image: docker:stable
  stage: build
  script:
    - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master
